# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: myappuser1
  password: myappuser1

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: myappuser1
  password: myappuser1

production:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: myappuser1
  password: myappuser1
